name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, cl]
        include:
          - os: windows-latest
            cpp_compiler: cl
          - os: ubuntu-latest
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4

    - name: Setup Conan
      uses: jwidauer/setup-conan@v1
          
    - name: BuildFmu
      run: ./buildfmu

    - uses: actions/upload-artifact@v4
      with:
        name: fmu
        path: cmake-build-release/manipulator.fmu
