name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Conan
      uses: jwidauer/setup-conan@v1
          
    - name: BuildFmu-Linux
      if:  runner.os == 'Linux'
      run: source buildfmu

    - name: BuildFmu-Windows
      if: runner.os == 'Windows'
      run: ./buildfmu

    - uses: actions/upload-artifact@v4
      with:
        name: fmu-${{ runner.os }}
        path: cmake-build-release/manipulator.fmu
